# Generated by Django 5.2.4 on 2025-07-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
