# Generated by Django 5.2.15 on 2026-10-02 05:33

import user_authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_rename_contact_number_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user_authentication.models.user_profile_upload_path),
        ),
    ]
